name: laweh_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (إصدارات متوافقة مع speech_to_text)
  firebase_core: ^2.17.0
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_app_check: ^0.2.2

  # Features
  tflite_flutter: ^0.11.0
  image: ^3.3.0
  universal_html: ^2.2.4
  image_picker: ^1.2.0

  speech_to_text: ^7.3.0
  confetti: ^0.7.0
  font_awesome_flutter: ^10.6.0
  video_player: ^2.7.0
  flutter_tts: ^4.2.3

  flutter_localizations:
    sdk: flutter
  fluttermoji: ^1.0.2
  google_mlkit_text_recognition: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/signs/signs/
    - assets/sign-language.png
    - assets/startNowBanner.mp4
    - assets/banner2.jpg
    - assets/banner3.jpg
    - assets/thumb.png
    - assets/signs/signs/
    - assets/memoryGame.jpg
    - assets/buildWord.jpg
    - assets/learn.jpg
    - assets/default.png
    - assets/avatars/
    - assets/models/best_float16.tflite
    - assets/models/labelmap.txt
    - assets/labels.txt
